-- お知らせに登録順の内部連番(seq)を追加するマイグレーション
-- Supabase の SQL Editor で実行してください。何度実行しても安全です。

-- 1) カラム追加（まずはNULL許可）
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS seq bigint;

-- 2) 既存行を登録順(created_at)で採番
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at ASC, id ASC) AS rn
  FROM public.announcements
)
UPDATE public.announcements a
SET seq = o.rn
FROM ordered o
WHERE a.id = o.id AND a.seq IS NULL;

-- 3) NOT NULL 化
ALTER TABLE public.announcements ALTER COLUMN seq SET NOT NULL;

-- 4) 以降は自動採番（IDENTITY）。既にIDENTITY化済みならスキップ
DO $$
DECLARE next_val bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.announcements'::regclass
      AND attname = 'seq'
      AND attidentity <> ''
  ) THEN
    SELECT COALESCE(MAX(seq), 0) + 1 INTO next_val FROM public.announcements;
    EXECUTE format(
      'ALTER TABLE public.announcements ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      next_val
    );
  END IF;
END $$;
